server:
  port: 8001


spring:
  application:
    name: cloud-payment-service
    zipkin:
      base-url: http://localhost:9411
    sleuth:
      sampler:
      # 采样率 介于0到1，一般设置0.5
      probability: 1
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://192.168.255.152:3306/db2019?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: tangguo

mybatis:
  mapperLocations: classpath:mapper/*.xml
  type-aliases-package: com.haha.springcloud.entities

eureka:
  client:
    register-with-eureka: true
    fetchRegistry: true
    service-url:
      #      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka  #集群版
      defaultZone: http://eureka7001.com:7001/eureka
  instance:
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}
    prefer-ip-address: true
