server:
  port: 80

eureka:
  client:
    register-with-eureka: false
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka, http://eureka7002.com:7002/eureka
spring:
  application:
    name: cloud-order-feign-service

ribbon:
  ReadTimeout: 5000 #建立连接时间
  ConnectTimeout: 5000 #读取可用资源所用时间

logging:
  level:
    com.haha.springcloud.service.PaymentFeignService: debug